import type { ScrollyDoc } from '$lib/types/scrolly';
import { generateScopedCss, colorVarMap } from '$lib/scrolly-css';

/**
 * Generate a single self-contained .svelte file that renders the given scrolly.
 * It inlines the data + helpers and imports the @fundar libraries, so it can be
 * dropped into any Svelte 5 + Tailwind v4 + DaisyUI v5 project as a sketch.
 */
export function generateSvelteFile(scrolly: ScrollyDoc): string {
	const components = JSON.stringify(scrolly.components ?? [], null, 2);
	const theme = scrolly.theme ? JSON.stringify(scrolly.theme) : 'undefined';
	const title = (scrolly.title || 'Scrolly').replace(/\*\//g, '* /');
	const scopedCss = generateScopedCss(scrolly.css).replace(/<\/style>/g, '<\\/style>');
	const colorMap = JSON.stringify(colorVarMap(scrolly.css));

	return `<!--
  ${title} — self-contained scrollytelling sketch generated by Scrollyboard.

  Requirements (npm install):
    @fundar/data-scrolly-telling @fundar/data-chart-telling svelteplot papaparse
  Plus Tailwind CSS v4 and DaisyUI v5 configured in your app's CSS, e.g.:
    @import "tailwindcss";
    @plugin "daisyui" { themes: all; }
-->
<script>
  import { onMount } from 'svelte';
  import { writable } from 'svelte/store';
  import { Scrolly, Layer, Step, Overlay, SideBySide, Slide } from '@fundar/data-scrolly-telling';
  import {
    LineChart, BarChart, HeatmapChart, PyramidChart,
    LinePlot, BarPlot, HeatmapPlot, PyramidPlot,
    DeltaMarker, PeakMarker
  } from '@fundar/data-chart-telling';
  import Papa from 'papaparse';

  const components = ${components};
  const theme = ${theme};
  const colorMap = ${colorMap};
  const scopedCss = ${JSON.stringify(scopedCss)};

  const threshold = writable({ type: 'percentage', value: 50 });

  function resolveColors(v) {
    if (typeof v === 'string') { const m = /^var\\(--([^)]+)\\)$/.exec(v.trim()); return m ? (colorMap[m[1]] ?? v) : v; }
    if (Array.isArray(v)) return v.map(resolveColors);
    if (v && typeof v === 'object') { const o = {}; for (const k in v) o[k] = resolveColors(v[k]); return o; }
    return v;
  }

  // Render charts only on the client (svelteplot needs the DOM).
  let mounted = $state(false);
  onMount(() => (mounted = true));

  // --- variant resolution (DaisyUI semantic colors) ---
  const BG = {
    'base-100': 'bg-base-100', 'base-200': 'bg-base-200', 'base-300': 'bg-base-300',
    neutral: 'bg-neutral', primary: 'bg-primary', secondary: 'bg-secondary', accent: 'bg-accent',
    info: 'bg-info', success: 'bg-success', warning: 'bg-warning', error: 'bg-error'
  };
  const CONTENT = {
    'base-100': 'text-base-content', 'base-200': 'text-base-content', 'base-300': 'text-base-content',
    neutral: 'text-neutral-content', primary: 'text-primary-content', secondary: 'text-secondary-content',
    accent: 'text-accent-content', info: 'text-info-content', success: 'text-success-content',
    warning: 'text-warning-content', error: 'text-error-content'
  };
  const TEXT = {
    'base-content': 'text-base-content', neutral: 'text-neutral', primary: 'text-primary',
    secondary: 'text-secondary', accent: 'text-accent', info: 'text-info',
    success: 'text-success', warning: 'text-warning', error: 'text-error'
  };
  const bgToken = (v) => (!v ? undefined : v.startsWith('bg-') ? v.slice(3) : v);
  function resolveBg(v, fallback) {
    const t = bgToken(v);
    return (t && BG[t]) || BG[fallback || 'base-100'];
  }
  function resolveText(tv, bv, fb) {
    if (tv) { if (tv.startsWith('text-')) return tv; if (TEXT[tv]) return TEXT[tv]; }
    const t = bgToken(bv);
    return (t && CONTENT[t]) || CONTENT[fb || 'base-100'];
  }

  const HEADING = { 1: 'text-4xl md:text-5xl', 2: 'text-3xl md:text-4xl', 3: 'text-2xl md:text-3xl', 4: 'text-xl md:text-2xl' };
  const COLS = { 1: 'grid-cols-1', 2: 'grid-cols-2', 3: 'grid-cols-3', 4: 'grid-cols-4' };

  // --- chart helpers ---
  function parseCsv(csv) {
    if (!csv || !csv.trim()) return [];
    const r = Papa.parse(csv, { header: true, skipEmptyLines: true });
    return r.data.map((row) => {
      const out = {};
      for (const k in row) { const n = Number(row[k]); out[k] = row[k] !== '' && !isNaN(n) ? n : row[k]; }
      return out;
    });
  }
  function chartComponent(c) {
    const isChart = c.variant === 'chart';
    if (c.chartType === 'bar') return isChart ? BarChart : BarPlot;
    if (c.chartType === 'heatmap') return isChart ? HeatmapChart : HeatmapPlot;
    if (c.chartType === 'pyramid') return isChart ? PyramidChart : PyramidPlot;
    return isChart ? LineChart : LinePlot;
  }
  const isEmpty = (o) => !o || (typeof o === 'object' && Object.keys(o).length === 0);
  function axisScale(a) {
    if (!a) return undefined;
    const s = {};
    if (a.type && a.type !== 'auto') s.type = a.type;
    if (a.label) s.label = a.label;
    if (a.domainMin !== undefined && a.domainMax !== undefined) s.domain = [a.domainMin, a.domainMax];
    for (const k of ['reverse', 'nice', 'zero', 'percent', 'grid']) if (a[k]) s[k] = true;
    if (a.tickRotate !== undefined) s.tickRotate = a.tickRotate;
    if (a.tickSpacing !== undefined) s.tickSpacing = a.tickSpacing;
    return Object.keys(s).length ? s : undefined;
  }
  function buildChartProps(c, rows) {
    const p = { data: rows, x: c.x, y: c.y, width: c.width || 600, height: c.height || 400 };
    if (c.z) p.z = c.z;
    if (c.variant === 'chart') {
      if (c.title) p.title = c.title;
      if (c.subtitle) p.subtitle = c.subtitle;
      if (c.caption) p.caption = c.caption;
      if (c.legend && c.legend.length) p.legend = c.legend;
      if (c.facet && c.facet.by) p.facet = c.facet;
      if (c.timeline && c.timeline.accessor) p.timeline = c.timeline;
    }
    if (c.segments && Object.keys(c.segments).length) {
      p.segments = resolveColors(c.segments);
    }
    if (c.markers && c.markers.length) p.markers = mapMarkers(resolveColors(c.markers), c);
    const sc = {};
    const sx = axisScale(c.scales && c.scales.x), sy = axisScale(c.scales && c.scales.y), sz = axisScale(c.scales && c.scales.z);
    if (sx) sc.x = sx; if (sy) sc.y = sy; if (sz) sc.z = sz;
    if (Object.keys(sc).length) p.scales = sc;
    if (!isEmpty(c.margins)) p.margins = c.margins;
    const st = {};
    if (c.styles && !isEmpty(c.styles.values)) st.values = resolveColors(c.styles.values);
    if (c.styles && !isEmpty(c.styles.colors)) st.colors = resolveColors(c.styles.colors);
    if (Object.keys(st).length) p.styles = st;
    return p;
  }
  function sceneLayout(l) { return l === 'side-by-side' ? SideBySide : l === 'slide' ? Slide : Overlay; }
  function mapMarkers(markers, c) {
    return markers.map((m) => {
      if (m.type === 'delta' || m.type === 'peak') {
        const props = { ...m };
        delete props.type; delete props.series; delete props.scope;
        if (m.type === 'peak') { props.xProp = props.xProp || c.x; props.yProp = props.yProp || c.y; }
        return { type: 'component', component: m.type === 'delta' ? DeltaMarker : PeakMarker,
          props, series: m.series || 'series', scope: m.scope || 'series' };
      }
      return m;
    });
  }
</script>

{#snippet chartBlock(c)}
  {@const rows = parseCsv(c.csvData)}
  {@const Comp = chartComponent(c)}
  {#if mounted && rows.length && c.x && c.y}
    <Comp {...buildChartProps(c, rows)} />
  {/if}
{/snippet}

{@html '<style>' + scopedCss + '</style>'}

<div data-theme={theme} class="scrolly-root min-h-screen bg-base-100">
  {#each components as c}
    {#if c.type === 'navbar'}
      {@const bg = resolveBg(c.bg ?? c.bgColor, 'base-100')}
      {@const text = resolveText(c.textColor, c.bg ?? c.bgColor, 'base-100')}
      <div class={'navbar ' + bg + ' ' + text + ' shadow-sm'}>
        <div class="flex-1"><h1 class="text-xl font-bold">{c.title}</h1></div>
        <div class="gap-2">
          {#each c.links ?? [] as l}<a href={l.href} class="btn btn-ghost btn-sm">{l.label}</a>{/each}
        </div>
      </div>

    {:else if c.type === 'hero'}
      {@const useCustom = !!(c.gradient || c.bgImage)}
      {@const bg = useCustom ? '' : resolveBg(c.bg, 'primary')}
      {@const text = resolveText(c.textColor, useCustom ? undefined : (c.bg ?? 'primary'), 'primary')}
      <div
        class={'hero relative overflow-hidden min-h-80 ' + bg + ' ' + text}
        style={(c.gradient ? 'background: ' + c.gradient + ';' : '') + (c.height ? 'min-height: ' + c.height + ';' : '')}
      >
        {#if c.bgImage && !c.gradient}
          <img src={c.bgImage} alt="" class="absolute inset-0 w-full h-full object-cover" />
        {/if}
        <div class="hero-content text-center relative z-10"><div class="max-w-md">
          <h1 class="text-5xl font-bold">{c.title}</h1>
          {#if c.subtitle}<p class="py-6 opacity-90">{c.subtitle}</p>{/if}
        </div></div>
      </div>

    {:else if c.type === 'footer'}
      {@const bg = resolveBg(c.bg ?? c.bgColor, 'base-200')}
      {@const text = resolveText(c.textColor, c.bg ?? c.bgColor, 'base-200')}
      <footer class={'footer ' + bg + ' ' + text + ' p-10'}>
        <div class={'grid gap-8 w-full max-w-full ' + (COLS[Math.max(1, Math.min((c.columns ?? []).length, 4))])}>
          {#each c.columns ?? [] as col}
            <div><span class="footer-title text-lg font-bold">{col.heading}</span><p>{col.text}</p></div>
          {/each}
        </div>
      </footer>

    {:else if c.type === 'divider'}
      {@const bg = resolveBg(c.bg, 'base-100')}
      {@const text = resolveText(c.textColor ?? c.color, c.bg, 'base-100')}
      <div class={'py-12 ' + bg}><div class="container mx-auto px-4 text-center">
        {#if c.level === 1}<h1 class={'font-bold ' + HEADING[1] + ' ' + text}>{c.text}</h1>
        {:else if c.level === 3}<h3 class={'font-bold ' + HEADING[3] + ' ' + text}>{c.text}</h3>
        {:else if c.level === 4}<h4 class={'font-bold ' + HEADING[4] + ' ' + text}>{c.text}</h4>
        {:else}<h2 class={'font-bold ' + HEADING[2] + ' ' + text}>{c.text}</h2>{/if}
      </div></div>

    {:else if c.type === 'paragraph'}
      {@const bg = resolveBg(c.bg, 'base-100')}
      {@const text = resolveText(c.textColor, c.bg, 'base-100')}
      <div class={'py-8 ' + bg}><div class="container mx-auto px-4 max-w-3xl">
        <div class={'prose-sm max-w-none text-base leading-relaxed ' + text}>{@html c.content}</div>
      </div></div>

    {:else if c.type === 'image'}
      <figure class="py-8"><div class="container mx-auto px-4 max-w-3xl">
        {#if c.src}<img src={c.src} alt={c.alt} class="rounded-lg w-full object-cover max-h-96" />{/if}
        {#if c.caption}<figcaption class="text-center text-sm mt-2 text-base-content/60">{c.caption}</figcaption>{/if}
      </div></figure>

    {:else if c.type === 'chart'}
      <div class="py-8 bg-base-100 chart-host"><div class="container mx-auto px-4 flex justify-center">
        {@render chartBlock(c)}
      </div></div>

    {:else if c.type === 'scene'}
      {#snippet dataLayer()}
        <Layer fill>
          {#if c.data.kind === 'text'}
            <div class="flex items-center justify-center w-full h-full bg-gradient-to-br from-primary/10 to-secondary/10">
              <p class="text-center px-8 text-lg">{c.data.content}</p>
            </div>
          {:else if c.data.kind === 'image'}
            <img src={c.data.src} alt={c.data.alt} class="w-full h-full object-cover" />
          {:else if c.data.kind === 'chart'}
            <div class="chart-host flex items-center justify-center w-full h-full overflow-auto p-4">
              {@render chartBlock(c.data)}
            </div>
          {/if}
        </Layer>
      {/snippet}
      {#snippet telling()}
        {#each c.steps ?? [] as step}
          <Step threshold={$threshold}><p class="prose max-w-md">{step.text}</p></Step>
        {/each}
      {/snippet}
      <div class="min-h-96">
        <Scrolly layout={sceneLayout(c.layout)} layoutProps={c.layoutProps} data={dataLayer} telling={telling} cssClass="scene" />
      </div>
    {/if}
  {/each}
</div>

<style>
  .chart-host :global(svg) { max-width: 100%; height: auto; }
  :global(.scene [data-telling-step]) {
    --step-padding: 2rem;
    --step-background-color: var(--color-base-100);
    --step-border-radius: 8px;
    --step-max-width: 600px;
    --step-margin-y: 50vh;
    --step-margin-x: auto;
  }
</style>
`;
}
